// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using indexTable.DataLayer;

#nullable disable

namespace indexTable.Migrations
{
    [DbContext(typeof(ProjeDbContext))]
    [Migration("20240513152339_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("indexTable.Models.hesaplanmisOranlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("degisimOrani")
                        .HasColumnType("float");

                    b.Property<double>("dolarizasyonEtkisiYüzde")
                        .HasColumnType("float");

                    b.Property<double>("dolarizasyonOncekiAyaGoreArtis")
                        .HasColumnType("float");

                    b.Property<double>("dolarizasyonVarlikDegisimOrani")
                        .HasColumnType("float");

                    b.Property<double>("dolarizasyonVarlikTutari")
                        .HasColumnType("float");

                    b.Property<double>("endeksOran")
                        .HasColumnType("float");

                    b.Property<double>("enflasyonEtkisiYüzde")
                        .HasColumnType("float");

                    b.Property<double>("enflasyonOncekiAyaGorevarlikArtis")
                        .HasColumnType("float");

                    b.Property<double>("enflasyonVarlikDegisimOrani")
                        .HasColumnType("float");

                    b.Property<double>("enflasyonVarlikTutari")
                        .HasColumnType("float");

                    b.Property<double>("oncekiAyaGoreArtis")
                        .HasColumnType("float");

                    b.Property<double>("varlikTarihiDolarKuru")
                        .HasColumnType("float");

                    b.Property<double>("varlikTutari")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("hesaplanmisOranlars");
                });

            modelBuilder.Entity("indexTable.Models.kurBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("kurBilgis");
                });

            modelBuilder.Entity("indexTable.Models.ufeEndeks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("dolarKuru")
                        .HasColumnType("float");

                    b.Property<double>("endeksOrani")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("tufeEndeks");
                });

            modelBuilder.Entity("indexTable.Models.varlikBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("Tutari")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("varlikBilgis");
                });
#pragma warning restore 612, 618
        }
    }
}
